// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"shuuen-backend/internal/model"

	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Course = struct {
	ID              field.Number[uint]
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field[gorm.DeletedAt]
	Name            field.String
	Description     field.String
	Author          field.String
	IsPublic        field.Bool
	SortOrder       field.Number[int]
	StructureSource field.String
	Modes           field.Slice[model.CourseMode]
}{
	ID:              field.Number[uint]{}.WithColumn("id"),
	CreatedAt:       field.Time{}.WithColumn("created_at"),
	UpdatedAt:       field.Time{}.WithColumn("updated_at"),
	DeletedAt:       field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:            field.String{}.WithColumn("name"),
	Description:     field.String{}.WithColumn("description"),
	Author:          field.String{}.WithColumn("author"),
	IsPublic:        field.Bool{}.WithColumn("is_public"),
	SortOrder:       field.Number[int]{}.WithColumn("sort_order"),
	StructureSource: field.String{}.WithColumn("structure_source"),
	Modes:           field.Slice[model.CourseMode]{}.WithName("Modes"),
}

var CourseMode = struct {
	ID             field.Number[uint]
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field[gorm.DeletedAt]
	CourseID       field.Number[uint]
	Mode           field.String
	LibraryGroupID field.Number[uint]
	LibraryGroup   field.Struct[model.LibraryGroup]
	Name           field.String
	Description    field.String
	SortOrder      field.Number[int]
	Groups         field.Slice[model.CourseProgressionGroup]
}{
	ID:             field.Number[uint]{}.WithColumn("id"),
	CreatedAt:      field.Time{}.WithColumn("created_at"),
	UpdatedAt:      field.Time{}.WithColumn("updated_at"),
	DeletedAt:      field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	CourseID:       field.Number[uint]{}.WithColumn("course_id"),
	Mode:           field.String{}.WithColumn("mode"),
	LibraryGroupID: field.Number[uint]{}.WithColumn("library_group_id"),
	LibraryGroup:   field.Struct[model.LibraryGroup]{}.WithName("LibraryGroup"),
	Name:           field.String{}.WithColumn("name"),
	Description:    field.String{}.WithColumn("description"),
	SortOrder:      field.Number[int]{}.WithColumn("sort_order"),
	Groups:         field.Slice[model.CourseProgressionGroup]{}.WithName("Groups"),
}

var CourseProgressionGroup = struct {
	ID             field.Number[uint]
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field[gorm.DeletedAt]
	CourseModeID   field.Number[uint]
	PublicID       field.String
	LibraryGroupID field.Number[uint]
	LibraryGroup   field.Struct[model.LibraryGroup]
	Name           field.String
	Description    field.String
	SortOrder      field.Number[int]
	Levels         field.Slice[model.CourseLevel]
}{
	ID:             field.Number[uint]{}.WithColumn("id"),
	CreatedAt:      field.Time{}.WithColumn("created_at"),
	UpdatedAt:      field.Time{}.WithColumn("updated_at"),
	DeletedAt:      field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	CourseModeID:   field.Number[uint]{}.WithColumn("course_mode_id"),
	PublicID:       field.String{}.WithColumn("public_id"),
	LibraryGroupID: field.Number[uint]{}.WithColumn("library_group_id"),
	LibraryGroup:   field.Struct[model.LibraryGroup]{}.WithName("LibraryGroup"),
	Name:           field.String{}.WithColumn("name"),
	Description:    field.String{}.WithColumn("description"),
	SortOrder:      field.Number[int]{}.WithColumn("sort_order"),
	Levels:         field.Slice[model.CourseLevel]{}.WithName("Levels"),
}

var CourseLevel = struct {
	ID                    field.String
	CreatedAt             field.Time
	UpdatedAt             field.Time
	DeletedAt             field.Field[gorm.DeletedAt]
	ProgressionGroupID    field.Number[uint]
	ProgressionGroup      field.Struct[model.CourseProgressionGroup]
	Name                  field.String
	Source                field.String
	Definition            field.Field[model.JSONDocument]
	SortOrder             field.Number[int]
	IsPublic              field.Bool
	LibraryMelodyID       field.Number[uint]
	LibraryMelody         field.Struct[model.Melody]
	LibraryVariantID      field.Number[uint]
	LibraryVariant        field.Struct[model.FileVariant]
	SectionLibraryGroupID field.Number[uint]
	SectionLibraryGroup   field.Struct[model.LibraryGroup]
}{
	ID:                    field.String{}.WithColumn("id"),
	CreatedAt:             field.Time{}.WithColumn("created_at"),
	UpdatedAt:             field.Time{}.WithColumn("updated_at"),
	DeletedAt:             field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	ProgressionGroupID:    field.Number[uint]{}.WithColumn("progression_group_id"),
	ProgressionGroup:      field.Struct[model.CourseProgressionGroup]{}.WithName("ProgressionGroup"),
	Name:                  field.String{}.WithColumn("name"),
	Source:                field.String{}.WithColumn("source"),
	Definition:            field.Field[model.JSONDocument]{}.WithColumn("definition"),
	SortOrder:             field.Number[int]{}.WithColumn("sort_order"),
	IsPublic:              field.Bool{}.WithColumn("is_public"),
	LibraryMelodyID:       field.Number[uint]{}.WithColumn("library_melody_id"),
	LibraryMelody:         field.Struct[model.Melody]{}.WithName("LibraryMelody"),
	LibraryVariantID:      field.Number[uint]{}.WithColumn("library_variant_id"),
	LibraryVariant:        field.Struct[model.FileVariant]{}.WithName("LibraryVariant"),
	SectionLibraryGroupID: field.Number[uint]{}.WithColumn("section_library_group_id"),
	SectionLibraryGroup:   field.Struct[model.LibraryGroup]{}.WithName("SectionLibraryGroup"),
}
