// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"shuuen-backend/internal/model"

	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Base = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var User = struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	Username     field.String
	UsernameKey  field.String
	DisplayName  field.String
	PasswordHash field.String
	Role         field.String
	TokenVersion field.Number[uint]
}{
	ID:           field.Number[uint]{}.WithColumn("id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Username:     field.String{}.WithColumn("username"),
	UsernameKey:  field.String{}.WithColumn("username_key"),
	DisplayName:  field.String{}.WithColumn("display_name"),
	PasswordHash: field.String{}.WithColumn("password_hash"),
	Role:         field.String{}.WithColumn("role"),
	TokenVersion: field.Number[uint]{}.WithColumn("token_version"),
}

var LibraryGroup = struct {
	ID          field.Number[uint]
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
	ParentID    field.Number[uint]
	Parent      field.Struct[model.LibraryGroup]
	Path        field.String
	Name        field.String
	Slug        field.String
	Description field.String
	SortOrder   field.Number[int]
	IsPublic    field.Bool
	ScanID      field.String
	Tags        field.Slice[model.Tag]
	Children    field.Slice[model.LibraryGroup]
	Melodies    field.Slice[model.Melody]
}{
	ID:          field.Number[uint]{}.WithColumn("id"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	ParentID:    field.Number[uint]{}.WithColumn("parent_id"),
	Parent:      field.Struct[model.LibraryGroup]{}.WithName("Parent"),
	Path:        field.String{}.WithColumn("path"),
	Name:        field.String{}.WithColumn("name"),
	Slug:        field.String{}.WithColumn("slug"),
	Description: field.String{}.WithColumn("description"),
	SortOrder:   field.Number[int]{}.WithColumn("sort_order"),
	IsPublic:    field.Bool{}.WithColumn("is_public"),
	ScanID:      field.String{}.WithColumn("scan_id"),
	Tags:        field.Slice[model.Tag]{}.WithName("Tags"),
	Children:    field.Slice[model.LibraryGroup]{}.WithName("Children"),
	Melodies:    field.Slice[model.Melody]{}.WithName("Melodies"),
}

var Tag = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	Name      field.String
	Slug      field.String
	Color     field.String
	Melodies  field.Slice[model.Melody]
	Groups    field.Slice[model.LibraryGroup]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Name:      field.String{}.WithColumn("name"),
	Slug:      field.String{}.WithColumn("slug"),
	Color:     field.String{}.WithColumn("color"),
	Melodies:  field.Slice[model.Melody]{}.WithName("Melodies"),
	Groups:    field.Slice[model.LibraryGroup]{}.WithName("Groups"),
}

var Melody = struct {
	ID          field.Number[uint]
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field[gorm.DeletedAt]
	GroupID     field.Number[uint]
	Group       field.Struct[model.LibraryGroup]
	SourcePath  field.String
	FileStem    field.String
	Title       field.String
	Slug        field.String
	Description field.String
	Composer    field.String
	Difficulty  field.String
	SortOrder   field.Number[int]
	IsPublic    field.Bool
	ScanID      field.String
	Tags        field.Slice[model.Tag]
	Variants    field.Slice[model.FileVariant]
}{
	ID:          field.Number[uint]{}.WithColumn("id"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	DeletedAt:   field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	GroupID:     field.Number[uint]{}.WithColumn("group_id"),
	Group:       field.Struct[model.LibraryGroup]{}.WithName("Group"),
	SourcePath:  field.String{}.WithColumn("source_path"),
	FileStem:    field.String{}.WithColumn("file_stem"),
	Title:       field.String{}.WithColumn("title"),
	Slug:        field.String{}.WithColumn("slug"),
	Description: field.String{}.WithColumn("description"),
	Composer:    field.String{}.WithColumn("composer"),
	Difficulty:  field.String{}.WithColumn("difficulty"),
	SortOrder:   field.Number[int]{}.WithColumn("sort_order"),
	IsPublic:    field.Bool{}.WithColumn("is_public"),
	ScanID:      field.String{}.WithColumn("scan_id"),
	Tags:        field.Slice[model.Tag]{}.WithName("Tags"),
	Variants:    field.Slice[model.FileVariant]{}.WithName("Variants"),
}

var FileVariant = struct {
	ID           field.Number[uint]
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field[gorm.DeletedAt]
	MelodyID     field.Number[uint]
	Melody       field.Struct[model.Melody]
	Format       field.String
	OriginalName field.String
	StoredName   field.String
	StoragePath  field.String
	MimeType     field.String
	SizeBytes    field.Number[int64]
	FileModTime  field.Number[int64]
	ChecksumSHA  field.String
	IsPrimary    field.Bool
	ScanID       field.String
}{
	ID:           field.Number[uint]{}.WithColumn("id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
	DeletedAt:    field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	MelodyID:     field.Number[uint]{}.WithColumn("melody_id"),
	Melody:       field.Struct[model.Melody]{}.WithName("Melody"),
	Format:       field.String{}.WithColumn("format"),
	OriginalName: field.String{}.WithColumn("original_name"),
	StoredName:   field.String{}.WithColumn("stored_name"),
	StoragePath:  field.String{}.WithColumn("storage_path"),
	MimeType:     field.String{}.WithColumn("mime_type"),
	SizeBytes:    field.Number[int64]{}.WithColumn("size_bytes"),
	FileModTime:  field.Number[int64]{}.WithColumn("file_mod_time"),
	ChecksumSHA:  field.String{}.WithColumn("checksum_sha"),
	IsPrimary:    field.Bool{}.WithColumn("is_primary"),
	ScanID:       field.String{}.WithColumn("scan_id"),
}
