// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"shuuen-backend/internal/model"

	"gorm.io/cli/gorm/field"
)

var UserSyncState = struct {
	UserID                  field.Number[uint]
	User                    field.Struct[model.User]
	Revision                field.Number[int64]
	TrainingSessionRevision field.Number[int64]
	CreatedAt               field.Time
	UpdatedAt               field.Time
}{
	UserID:                  field.Number[uint]{}.WithColumn("user_id"),
	User:                    field.Struct[model.User]{}.WithName("User"),
	Revision:                field.Number[int64]{}.WithColumn("revision"),
	TrainingSessionRevision: field.Number[int64]{}.WithColumn("training_session_revision"),
	CreatedAt:               field.Time{}.WithColumn("created_at"),
	UpdatedAt:               field.Time{}.WithColumn("updated_at"),
}

var UserLevel = struct {
	ID         field.Number[uint]
	UserID     field.Number[uint]
	User       field.Struct[model.User]
	Kind       field.String
	LevelID    field.String
	Name       field.String
	Source     field.String
	Definition field.Field[model.JSONDocument]
	Revision   field.Number[int64]
	Deleted    field.Bool
	CreatedAt  field.Time
	UpdatedAt  field.Time
}{
	ID:         field.Number[uint]{}.WithColumn("id"),
	UserID:     field.Number[uint]{}.WithColumn("user_id"),
	User:       field.Struct[model.User]{}.WithName("User"),
	Kind:       field.String{}.WithColumn("kind"),
	LevelID:    field.String{}.WithColumn("level_id"),
	Name:       field.String{}.WithColumn("name"),
	Source:     field.String{}.WithColumn("source"),
	Definition: field.Field[model.JSONDocument]{}.WithColumn("definition"),
	Revision:   field.Number[int64]{}.WithColumn("revision"),
	Deleted:    field.Bool{}.WithColumn("deleted"),
	CreatedAt:  field.Time{}.WithColumn("created_at"),
	UpdatedAt:  field.Time{}.WithColumn("updated_at"),
}

var UserTrainingSession = struct {
	ID                     field.Number[uint]
	UserID                 field.Number[uint]
	User                   field.Struct[model.User]
	SessionID              field.String
	Flow                   field.String
	LevelID                field.String
	LevelName              field.String
	CompletedAtEpochMillis field.Number[int64]
	FinishedEarly          field.Bool
	QuestionsAnswered      field.Number[int]
	NotesTotal             field.Number[int]
	CorrectNotes           field.Number[int]
	MissedNotes            field.Number[int]
	Replays                field.Number[int]
	DurationMillis         field.Number[int64]
	AvgAnswerMillis        field.Number[int64]
	AvgDeltaMillis         field.Number[int64]
	BestStreak             field.Number[int]
	KeysPracticed          field.Number[int]
	QuestionResults        field.Field[model.JSONDocument]
	Revision               field.Number[int64]
	Deleted                field.Bool
	CreatedAt              field.Time
	UpdatedAt              field.Time
}{
	ID:                     field.Number[uint]{}.WithColumn("id"),
	UserID:                 field.Number[uint]{}.WithColumn("user_id"),
	User:                   field.Struct[model.User]{}.WithName("User"),
	SessionID:              field.String{}.WithColumn("session_id"),
	Flow:                   field.String{}.WithColumn("flow"),
	LevelID:                field.String{}.WithColumn("level_id"),
	LevelName:              field.String{}.WithColumn("level_name"),
	CompletedAtEpochMillis: field.Number[int64]{}.WithColumn("completed_at_epoch_millis"),
	FinishedEarly:          field.Bool{}.WithColumn("finished_early"),
	QuestionsAnswered:      field.Number[int]{}.WithColumn("questions_answered"),
	NotesTotal:             field.Number[int]{}.WithColumn("notes_total"),
	CorrectNotes:           field.Number[int]{}.WithColumn("correct_notes"),
	MissedNotes:            field.Number[int]{}.WithColumn("missed_notes"),
	Replays:                field.Number[int]{}.WithColumn("replays"),
	DurationMillis:         field.Number[int64]{}.WithColumn("duration_millis"),
	AvgAnswerMillis:        field.Number[int64]{}.WithColumn("avg_answer_millis"),
	AvgDeltaMillis:         field.Number[int64]{}.WithColumn("avg_delta_millis"),
	BestStreak:             field.Number[int]{}.WithColumn("best_streak"),
	KeysPracticed:          field.Number[int]{}.WithColumn("keys_practiced"),
	QuestionResults:        field.Field[model.JSONDocument]{}.WithColumn("question_results"),
	Revision:               field.Number[int64]{}.WithColumn("revision"),
	Deleted:                field.Bool{}.WithColumn("deleted"),
	CreatedAt:              field.Time{}.WithColumn("created_at"),
	UpdatedAt:              field.Time{}.WithColumn("updated_at"),
}
